coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
comment:
  require_changes: true
  layout: "condensed_header, condensed_files, condensed_footer"
  hide_project_coverage: true
