create sequence "HIBERNATE_SEQUENCE";

create table "WORKSPACE" (
    "ID"                     bigint generated by default as identity not null,
    "VERSION"                integer                                 not null,
    "NAME"                   character varying(255)                  not null,
    "OWNER_ID"               bigint                                  not null,
    "TAX_ENABLED"            boolean                                 not null,
    "MULTI_CURRENCY_ENABLED" boolean                                 not null,
    "DEFAULT_CURRENCY"       character varying(3)                    not null
);
alter table "WORKSPACE"
    add primary key ("ID");

create table "INCOME" (
    "ID"                                                  bigint generated by default as identity not null,
    "VERSION"                                             integer                                 not null,
    "CONVERTED_ORIGINAL_AMOUNT_IN_DEFAULT_CURRENCY"       bigint,
    "CURRENCY"                                            character varying(3)                    not null,
    "DATE_RECEIVED"                                       date                                    not null,
    "TIME_RECORDED"                                       timestamp                               not null,
    "NOTES"                                               character varying(1024),
    "ORIGINAL_AMOUNT"                                     bigint                                  not null,
    "INCOME_TAXABLE_ORIGINAL_AMOUNT_IN_DEFAULT_CURRENCY"  bigint,
    "CATEGORY_ID"                                         bigint,
    "TITLE"                                               character varying(255)                  not null,
    "WORKSPACE_ID"                                        bigint                                  not null,
    "GENERAL_TAX_ID"                                      bigint,
    "GENERAL_TAX_AMOUNT"                                  bigint,
    "GENERAL_TAX_RATE_IN_BPS"                             integer,
    "USE_DIFFERENT_EXCHANGE_RATE_FOR_INCOME_TAX_PURPOSES" boolean                                 not null,
    "STATUS"                                              character varying(255)                  not null,
    "INCOME_TAXABLE_ADJUSTED_AMOUNT_IN_DEFAULT_CURRENCY"  bigint,
    "CONVERTED_ADJUSTED_AMOUNT_IN_DEFAULT_CURRENCY"       bigint,
    "LINKED_INVOICE_ID"                                   bigint
);
alter table "INCOME"
    add primary key ("ID");

create table "CUSTOMER" (
    "ID"           bigint generated by default as identity not null,
    "VERSION"      integer                                 not null,
    "NAME"         character varying(255)                  not null,
    "WORKSPACE_ID" bigint                                  not null
);
alter table "CUSTOMER"
    add primary key ("ID");

create table "CATEGORY" (
    "ID"           bigint generated by default as identity not null,
    "VERSION"      integer                                 not null,
    "DESCRIPTION"  character varying(1024),
    "EXPENSE"      boolean                                 not null,
    "INCOME"       boolean                                 not null,
    "NAME"         character varying(255)                  not null,
    "WORKSPACE_ID" bigint                                  not null
);
alter table "CATEGORY"
    add primary key ("ID");

create table "EXPENSE" (
    "ID"                                                  bigint generated by default as identity not null,
    "VERSION"                                             integer                                 not null,
    "INCOME_TAXABLE_ORIGINAL_AMOUNT_IN_DEFAULT_CURRENCY"  bigint,
    "CONVERTED_ORIGINAL_AMOUNT_IN_DEFAULT_CURRENCY"       bigint,
    "CURRENCY"                                            character varying(3)                    not null,
    "DATE_PAID"                                           date                                    not null,
    "TIME_RECORDED"                                       timestamp                               not null,
    "NOTES"                                               character varying(1024),
    "ORIGINAL_AMOUNT"                                     bigint                                  not null,
    "PERCENT_ON_BUSINESS"                                 integer                                 not null,
    "CATEGORY_ID"                                         bigint,
    "INCOME_TAXABLE_ADJUSTED_AMOUNT_IN_DEFAULT_CURRENCY"  bigint,
    "TITLE"                                               character varying(255)                  not null,
    "WORKSPACE_ID"                                        bigint                                  not null,
    "GENERAL_TAX_ID"                                      bigint,
    "GENERAL_TAX_AMOUNT"                                  bigint,
    "GENERAL_TAX_RATE_IN_BPS"                             integer,
    "USE_DIFFERENT_EXCHANGE_RATE_FOR_INCOME_TAX_PURPOSES" boolean                                 not null,
    "STATUS"                                              character varying(255)                  not null,
    "CONVERTED_ADJUSTED_AMOUNT_IN_DEFAULT_CURRENCY"       bigint
);
alter table "EXPENSE"
    add primary key ("ID");

create table "DOCUMENT" (
    "ID"               bigint generated by default as identity not null,
    "VERSION"          integer                                 not null,
    "TIME_UPLOADED"    timestamp                               not null,
    "NAME"             character varying(255)                  not null,
    "STORAGE_ID"       character varying(255)                  not null,
    "STORAGE_LOCATION" character varying(2048),
    "WORKSPACE_ID"     bigint                                  not null,
    "SIZE_IN_BYTES"    bigint
);
alter table "DOCUMENT"
    add primary key ("ID");

create table "EXPENSE_ATTACHMENTS" (
    "EXPENSE_ID"  bigint not null,
    "DOCUMENT_ID" bigint not null
);
alter table "EXPENSE_ATTACHMENTS"
    add primary key ("EXPENSE_ID", "DOCUMENT_ID");

create table "INCOME_ATTACHMENTS" (
    "INCOME_ID"   bigint not null,
    "DOCUMENT_ID" bigint not null
);
alter table "INCOME_ATTACHMENTS"
    add primary key ("INCOME_ID", "DOCUMENT_ID");

create table "INVOICE" (
    "ID"             bigint generated by default as identity not null,
    "VERSION"        integer                                 not null,
    "CUSTOMER_ID"    bigint                                  not null,
    "TITLE"          character varying(255)                  not null,
    "TIME_RECORDED"  timestamp                               not null,
    "DATE_ISSUED"    date                                    not null,
    "DATE_SENT"      date,
    "DATE_PAID"      date,
    "TIME_CANCELLED" timestamp,
    "DUE_DATE"       date                                    not null,
    "CURRENCY"       character varying(3)                    not null,
    "AMOUNT"         bigint                                  not null,
    "NOTES"          character varying(1024),
    "GENERAL_TAX_ID" bigint,
    "STATUS"         character varying(30)                   not null
);
alter table "INVOICE"
    add primary key ("ID");

create table "GENERAL_TAX" (
    "ID"           bigint generated by default as identity not null,
    "VERSION"      integer                                 not null,
    "TITLE"        character varying(255)                  not null,
    "DESCRIPTION"  character varying(255),
    "RATE_IN_BPS"  integer                                 not null,
    "WORKSPACE_ID" bigint                                  not null
);
alter table "GENERAL_TAX"
    add primary key ("ID");

create table "REFRESH_TOKEN" (
    "ID"              bigint generated by default as identity not null,
    "VERSION"         integer                                 not null,
    "EXPIRATION_TIME" timestamp                               not null,
    "TOKEN"           character varying(2048)                 not null,
    "USER_ID"         bigint                                  not null
);
alter table "REFRESH_TOKEN"
    add primary key ("ID");

create table "INVOICE_ATTACHMENTS" (
    "INVOICE_ID"  bigint not null,
    "DOCUMENT_ID" bigint not null
);
alter table "INVOICE_ATTACHMENTS"
    add primary key ("INVOICE_ID", "DOCUMENT_ID");

create table "PLATFORM_USER" (
    "ID"                             bigint generated by default as identity not null,
    "VERSION"                        integer                                 not null,
    "USER_NAME"                      character varying(255)                  not null,
    "PASSWORD_HASH"                  character varying(255)                  not null,
    "IS_ADMIN"                       boolean                                 not null,
    "DOCUMENTS_STORAGE"              character varying(255),
    "FAILED_ATTEMPTS_COUNT"          integer                                 not null,
    "TEMPORARY_LOCK_EXPIRATION_TIME" timestamp,
    "LANGUAGE"                       character varying(36)                   not null,
    "LOCALE"                         character varying(36)                   not null
);
alter table "PLATFORM_USER"
    add primary key ("ID");

create table "PERSISTENT_OAUTH2_AUTHORIZED_CLIENT_ACCESS_TOKEN_SCOPES" (
    "CLIENT_ID"           bigint not null,
    "ACCESS_TOKEN_SCOPES" character varying(255)
);

create table "INCOME_TAX_PAYMENT_ATTACHMENTS" (
    "INCOME_TAX_PAYMENT_ID" bigint not null,
    "DOCUMENT_ID"           bigint not null
);
alter table "INCOME_TAX_PAYMENT_ATTACHMENTS"
    add primary key ("INCOME_TAX_PAYMENT_ID", "DOCUMENT_ID");

create table "SAVED_WORKSPACE_ACCESS_TOKEN" (
    "ID"                        bigint generated by default as identity not null,
    "VERSION"                   integer                                 not null,
    "OWNER_ID"                  bigint                                  not null,
    "WORKSPACE_ACCESS_TOKEN_ID" bigint                                  not null
);
alter table "SAVED_WORKSPACE_ACCESS_TOKEN"
    add primary key ("ID");

create table "GOOGLE_DRIVE_STORAGE_INTEGRATION" (
    "ID"        bigint generated by default as identity not null,
    "VERSION"   integer                                 not null,
    "FOLDER_ID" character varying(255),
    "USER_ID"   bigint                                  not null
);
alter table "GOOGLE_DRIVE_STORAGE_INTEGRATION"
    add primary key ("ID");

create table "PERSISTENT_OAUTH2_AUTHORIZED_CLIENT" (
    "ID"                      bigint generated by default as identity not null,
    "VERSION"                 integer                                 not null,
    "ACCESS_TOKEN"            character varying(255)                  not null,
    "ACCESS_TOKEN_EXPIRES_AT" timestamp,
    "ACCESS_TOKEN_ISSUED_AT"  timestamp,
    "CLIENT_REGISTRATION_ID"  character varying(255)                  not null,
    "REFRESH_TOKEN"           character varying(255),
    "REFRESH_TOKEN_ISSUED_AT" timestamp,
    "USER_NAME"               character varying(255)                  not null
);
alter table "PERSISTENT_OAUTH2_AUTHORIZED_CLIENT"
    add primary key ("ID");

create table "WORKSPACE_ACCESS_TOKEN" (
    "ID"           bigint generated by default as identity not null,
    "VERSION"      integer                                 not null,
    "REVOKED"      boolean                                 not null,
    "TIME_CREATED" timestamp                               not null,
    "TOKEN"        character varying(255)                  not null,
    "VALID_TILL"   timestamp                               not null,
    "WORKSPACE_ID" bigint                                  not null
);
alter table "WORKSPACE_ACCESS_TOKEN"
    add primary key ("ID");

create table "INCOME_TAX_PAYMENT" (
    "ID"             bigint generated by default as identity not null,
    "VERSION"        integer                                 not null,
    "AMOUNT"         bigint                                  not null,
    "DATE_PAID"      date                                    not null,
    "TIME_RECORDED"  timestamp                               not null,
    "NOTES"          character varying(1024),
    "WORKSPACE_ID"   bigint                                  not null,
    "TITLE"          character varying(255)                  not null,
    "REPORTING_DATE" date                                    not null
);
alter table "INCOME_TAX_PAYMENT"
    add primary key ("ID");

alter table "WORKSPACE_ACCESS_TOKEN"
    add constraint "WORKSPACE_ACCESS_TOKEN_TOKEN_UQ" unique ("TOKEN");
alter table "GOOGLE_DRIVE_STORAGE_INTEGRATION"
    add constraint "GOOGLE_DRIVE_STORAGE_INTEGRATION_UQ" unique ("USER_ID");
alter table "DOCUMENT"
    add constraint "DOCUMENT_WORKSPACE_FK" foreign key ("WORKSPACE_ID") references "WORKSPACE" ("ID");
alter table "EXPENSE"
    add constraint "EXPENSE_GENERAL_TAX_FK" foreign key ("GENERAL_TAX_ID") references "GENERAL_TAX" ("ID");
alter table "INCOME"
    add constraint "INCOME_LINKED_INVOICE_FK" foreign key ("LINKED_INVOICE_ID") references "INVOICE" ("ID");
alter table "INVOICE"
    add constraint "INVOICE_GENERAL_TAX_FK" foreign key ("GENERAL_TAX_ID") references "GENERAL_TAX" ("ID");
alter table "SAVED_WORKSPACE_ACCESS_TOKEN"
    add constraint "SAVED_WS_ACCESS_TOKEN_OWNER_FK" foreign key ("OWNER_ID") references "PLATFORM_USER" ("ID");
alter table "INCOME_TAX_PAYMENT"
    add constraint "INCOME_TAX_PAYMENT_WORKSPACE_FK" foreign key ("WORKSPACE_ID") references "WORKSPACE" ("ID");
alter table "INVOICE_ATTACHMENTS"
    add constraint "INVOICE_ATTACHMENTS_INVOICE_FK" foreign key ("INVOICE_ID") references "INVOICE" ("ID");
alter table "INCOME"
    add constraint "INCOME_GENERAL_TAX_FK" foreign key ("GENERAL_TAX_ID") references "GENERAL_TAX" ("ID");
alter table "PERSISTENT_OAUTH2_AUTHORIZED_CLIENT_ACCESS_TOKEN_SCOPES"
    add constraint "PAUTH2AC_ACCESS_TOKEN_SCOPES_SCOPES_CLIENT_FK" foreign key ("CLIENT_ID") references "PERSISTENT_OAUTH2_AUTHORIZED_CLIENT" ("ID") on delete cascade;
alter table "SAVED_WORKSPACE_ACCESS_TOKEN"
    add constraint "SAVED_WS_ACCESS_TOKEN_WS_ACCESS_TOKEN_FK" foreign key ("WORKSPACE_ACCESS_TOKEN_ID") references "WORKSPACE_ACCESS_TOKEN" ("ID");
alter table "WORKSPACE"
    add constraint "WORKSPACE_OWNER_FK" foreign key ("OWNER_ID") references "PLATFORM_USER" ("ID");
alter table "EXPENSE_ATTACHMENTS"
    add constraint "EXPENSE_ATTACHMENTS_DOCUMENT_FK" foreign key ("DOCUMENT_ID") references "DOCUMENT" ("ID");
alter table "EXPENSE"
    add constraint "EXPENSE_WORKSPACE_FK" foreign key ("WORKSPACE_ID") references "WORKSPACE" ("ID");
alter table "INCOME_ATTACHMENTS"
    add constraint "INCOME_ATTACHMENTS_DOCUMENT_FK" foreign key ("DOCUMENT_ID") references "DOCUMENT" ("ID");
alter table "INCOME"
    add constraint "INCOME_WORKSPACE_FK" foreign key ("WORKSPACE_ID") references "WORKSPACE" ("ID");
alter table "INCOME"
    add constraint "INCOME_CATEGORY_FK" foreign key ("CATEGORY_ID") references "CATEGORY" ("ID");
alter table "CUSTOMER"
    add constraint "CUSTOMER_WORKSPACE_FK" foreign key ("WORKSPACE_ID") references "WORKSPACE" ("ID");
alter table "INVOICE"
    add constraint "INVOICE_CUSTOMER_FK" foreign key ("CUSTOMER_ID") references "CUSTOMER" ("ID");
alter table "INCOME_TAX_PAYMENT_ATTACHMENTS"
    add constraint "INCOME_TAX_PAYMENT_ATTACHMENTS_DOCUMENT_FK" foreign key ("DOCUMENT_ID") references "DOCUMENT" ("ID");
alter table "CATEGORY"
    add constraint "CATEGORY_WORKSPACE_FK" foreign key ("WORKSPACE_ID") references "WORKSPACE" ("ID");
alter table "GENERAL_TAX"
    add constraint "GENERAL_TAX_WORKSPACE_FK" foreign key ("WORKSPACE_ID") references "WORKSPACE" ("ID");
alter table "INCOME_ATTACHMENTS"
    add constraint "INCOME_ATTACHMENTS_INCOME_FK" foreign key ("INCOME_ID") references "INCOME" ("ID");
alter table "WORKSPACE_ACCESS_TOKEN"
    add constraint "WORKSPACE_ACCESS_TOKEN_WORKSPACE_FK" foreign key ("WORKSPACE_ID") references "WORKSPACE" ("ID");
alter table "INVOICE_ATTACHMENTS"
    add constraint "INVOICE_ATTACHMENTS_DOCUMENT_FK" foreign key ("DOCUMENT_ID") references "DOCUMENT" ("ID");
alter table "EXPENSE_ATTACHMENTS"
    add constraint "EXPENSE_ATTACHMENTS_EXPENSE_FK" foreign key ("EXPENSE_ID") references "EXPENSE" ("ID");
alter table "REFRESH_TOKEN"
    add constraint "REFRESH_TOKEN_USER_FK" foreign key ("USER_ID") references "PLATFORM_USER" ("ID");
alter table "EXPENSE"
    add constraint "EXPENSE_CATEGORY_FK" foreign key ("CATEGORY_ID") references "CATEGORY" ("ID");
alter table "GOOGLE_DRIVE_STORAGE_INTEGRATION"
    add constraint "GDRIVE_STORAGE_INTEGRATION_USER_FK" foreign key ("USER_ID") references "PLATFORM_USER" ("ID");
alter table "INCOME_TAX_PAYMENT_ATTACHMENTS"
    add constraint "INCOME_TAX_PAYMENT_ATTACHMENTS_TAX_PAYMENT_FK" foreign key ("INCOME_TAX_PAYMENT_ID") references "INCOME_TAX_PAYMENT" ("ID");
