/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/workspaces/{workspaceId}": {
    put: operations["editWorkspace"];
  };
  "/api/workspaces/{workspaceId}/invoices/{invoiceId}": {
    get: operations["getInvoice"];
    put: operations["updateInvoice"];
  };
  "/api/workspaces/{workspaceId}/incomes/{incomeId}": {
    get: operations["getIncome"];
    put: operations["updateIncome"];
  };
  "/api/workspaces/{workspaceId}/income-tax-payments/{taxPaymentId}": {
    get: operations["getTaxPayment"];
    put: operations["updateTaxPayment"];
  };
  "/api/workspaces/{workspaceId}/general-taxes/{taxId}": {
    get: operations["getTax"];
    put: operations["updateTax"];
  };
  "/api/workspaces/{workspaceId}/expenses/{expenseId}": {
    get: operations["getExpense"];
    put: operations["updateExpense"];
  };
  "/api/workspaces/{workspaceId}/customers/{customerId}": {
    get: operations["getCustomer"];
    put: operations["updateCustomer"];
  };
  "/api/profile": {
    get: operations["getProfile"];
    put: operations["updateProfile"];
  };
  "/api/workspaces": {
    get: operations["getWorkspaces"];
    post: operations["createWorkspace"];
  };
  "/api/workspaces/{workspaceId}/workspace-access-tokens": {
    get: operations["getAccessTokens"];
    post: operations["createToken"];
  };
  "/api/workspaces/{workspaceId}/invoices": {
    get: operations["getInvoices"];
    post: operations["createInvoice"];
  };
  "/api/workspaces/{workspaceId}/invoices/{invoiceId}/cancel": {
    post: operations["cancelInvoice"];
  };
  "/api/workspaces/{workspaceId}/incomes": {
    get: operations["getIncomes"];
    post: operations["createIncome"];
  };
  "/api/workspaces/{workspaceId}/income-tax-payments": {
    get: operations["getTaxPayments"];
    post: operations["createTaxPayment"];
  };
  "/api/workspaces/{workspaceId}/general-taxes": {
    get: operations["getTaxes"];
    post: operations["createTax"];
  };
  "/api/workspaces/{workspaceId}/expenses": {
    get: operations["getExpenses"];
    post: operations["createExpense"];
  };
  "/api/workspaces/{workspaceId}/documents": {
    get: operations["getDocuments"];
    post: operations["uploadNewDocument"];
  };
  "/api/workspaces/{workspaceId}/customers": {
    get: operations["getCustomers"];
    post: operations["createCustomer"];
  };
  "/api/workspaces/{workspaceId}/categories": {
    get: operations["getCategories"];
    post: operations["createCategory"];
  };
  "/api/users": {
    get: operations["getUsers"];
    post: operations["createUser"];
  };
  "/api/shared-workspaces": {
    get: operations["getSharedWorkspaces"];
    post: operations["saveSharedWorkspace"];
  };
  "/api/auth/token": {
    post: operations["refreshToken"];
  };
  "/api/auth/oauth2/callback": {
    post: operations["authCallback"];
  };
  "/api/auth/logout": {
    post: operations["logout"];
  };
  "/api/auth/login": {
    post: operations["login_1"];
  };
  "/api/workspaces/{workspaceId}/statistics/incomes": {
    get: operations["getIncomesStatistics"];
  };
  "/api/workspaces/{workspaceId}/statistics/income-tax-payments": {
    get: operations["getTaxPaymentsStatistics"];
  };
  "/api/workspaces/{workspaceId}/statistics/expenses": {
    get: operations["getExpensesStatistics"];
  };
  "/api/workspaces/{workspaceId}/statistics/currencies-shortlist": {
    get: operations["getCurrenciesShortlist"];
  };
  "/api/workspaces/{workspaceId}/reporting/general-taxes": {
    get: operations["getGeneralTaxReport"];
  };
  "/api/workspaces/{workspaceId}/documents/{documentId}/download-token": {
    get: operations["getDownloadToken"];
  };
  "/api/workspaces/{workspaceId}/documents/{documentId}/content": {
    get: operations["getDocumentContent"];
  };
  "/api/push-notifications": {
    get: operations["getPushNotificationMessages"];
  };
  "/api/profile/documents-storage": {
    get: operations["getDocumentsStorageStatus"];
  };
  "/api/downloads": {
    get: operations["getContent"];
  };
  "/api/storage/google-drive/status": {
    get: operations["getIntegrationStatus_1"];
    put: operations["getIntegrationStatus_6"];
    post: operations["getIntegrationStatus_3"];
    delete: operations["getIntegrationStatus_5"];
    options: operations["getIntegrationStatus"];
    head: operations["getIntegrationStatus_2"];
    patch: operations["getIntegrationStatus_4"];
  };
}

export interface components {
  schemas: {
    ErrorResponse: {
      errorId: string;
    };
    EditWorkspaceDto: {
      name: string;
    };
    WorkspaceDto: {
      id?: number;
      version: number;
      name: string;
      taxEnabled: boolean;
      multiCurrencyEnabled: boolean;
      defaultCurrency: string;
      editable: boolean;
    };
    EditInvoiceDto: {
      title: string;
      customer: number;
      dateIssued: string;
      dateSent?: string;
      datePaid?: string;
      dateCancelled?: string;
      dueDate: string;
      currency: string;
      amount: number;
      attachments?: number[];
      notes?: string;
      generalTax?: number;
    };
    InvoiceDto: {
      title: string;
      customer: number;
      timeRecorded: string;
      dateIssued: string;
      dateSent?: string;
      datePaid?: string;
      dueDate: string;
      currency: string;
      amount: number;
      attachments: number[];
      notes?: string;
      id: number;
      version: number;
      status: "DRAFT" | "SENT" | "OVERDUE" | "PAID" | "CANCELLED";
      generalTax?: number;
    };
    EditIncomeDto: {
      category?: number;
      dateReceived: string;
      title: string;
      currency: string;
      originalAmount: number;
      convertedAmountInDefaultCurrency?: number;
      useDifferentExchangeRateForIncomeTaxPurposes: boolean;
      incomeTaxableAmountInDefaultCurrency?: number;
      attachments?: number[];
      notes?: string;
      generalTax?: number;
      linkedInvoice?: number;
    };
    IncomeAmountsDto: {
      originalAmountInDefaultCurrency?: number;
      adjustedAmountInDefaultCurrency?: number;
    };
    IncomeDto: {
      category?: number;
      title: string;
      timeRecorded: string;
      dateReceived: string;
      currency: string;
      originalAmount: number;
      attachments: number[];
      notes?: string;
      id: number;
      version: number;
      status:
        | "FINALIZED"
        | "PENDING_CONVERSION"
        | "PENDING_CONVERSION_FOR_TAXATION_PURPOSES";
      linkedInvoice?: number;
      generalTax?: number;
      generalTaxRateInBps?: number;
      generalTaxAmount?: number;
      convertedAmounts: components["schemas"]["IncomeAmountsDto"];
      incomeTaxableAmounts: components["schemas"]["IncomeAmountsDto"];
      useDifferentExchangeRateForIncomeTaxPurposes: boolean;
    };
    EditIncomeTaxPaymentDto: {
      datePaid: string;
      reportingDate?: string;
      amount: number;
      attachments?: number[];
      notes?: string;
      title: string;
    };
    IncomeTaxPaymentDto: {
      id: number;
      version: number;
      title: string;
      timeRecorded: string;
      datePaid: string;
      reportingDate: string;
      amount: number;
      attachments: number[];
      notes?: string;
    };
    EditGeneralTaxDto: {
      title: string;
      description?: string;
      rateInBps: number;
    };
    GeneralTaxDto: {
      title: string;
      id: number;
      version: number;
      description?: string;
      rateInBps: number;
    };
    EditExpenseDto: {
      category?: number;
      datePaid: string;
      title: string;
      currency: string;
      originalAmount: number;
      convertedAmountInDefaultCurrency?: number;
      useDifferentExchangeRateForIncomeTaxPurposes: boolean;
      incomeTaxableAmountInDefaultCurrency?: number;
      attachments?: number[];
      percentOnBusiness?: number;
      notes?: string;
      generalTax?: number;
    };
    ExpenseAmountsDto: {
      originalAmountInDefaultCurrency?: number;
      adjustedAmountInDefaultCurrency?: number;
    };
    ExpenseDto: {
      category?: number;
      title: string;
      timeRecorded: string;
      datePaid: string;
      currency: string;
      originalAmount: number;
      attachments: number[];
      percentOnBusiness: number;
      notes?: string;
      id: number;
      version: number;
      status:
        | "FINALIZED"
        | "PENDING_CONVERSION"
        | "PENDING_CONVERSION_FOR_TAXATION_PURPOSES";
      generalTax?: number;
      generalTaxRateInBps?: number;
      generalTaxAmount?: number;
      convertedAmounts: components["schemas"]["ExpenseAmountsDto"];
      incomeTaxableAmounts: components["schemas"]["ExpenseAmountsDto"];
      useDifferentExchangeRateForIncomeTaxPurposes: boolean;
    };
    EditCustomerDto: {
      name: string;
    };
    CustomerDto: {
      name: string;
      id: number;
      version: number;
    };
    I18nSettingsDto: {
      locale: string;
      language: string;
    };
    UpdateProfileRequestDto: {
      documentsStorage?: string;
      i18n: components["schemas"]["I18nSettingsDto"];
    };
    ProfileDto: {
      userName: string;
      documentsStorage?: string;
      i18n: components["schemas"]["I18nSettingsDto"];
    };
    CreateWorkspaceDto: {
      name: string;
      defaultCurrency: string;
    };
    CreateWorkspaceAccessTokenDto: {
      validTill: string;
    };
    WorkspaceAccessTokenDto: {
      validTill: string;
      revoked: boolean;
      token: string;
      id: number;
      version: number;
    };
    DocumentDto: {
      id?: number;
      version: number;
      name: string;
      timeUploaded: string;
      sizeInBytes?: number;
    };
    CreateCategoryDto: {
      name: string;
      description?: string;
      income: boolean;
      expense: boolean;
    };
    CategoryDto: {
      id?: number;
      version: number;
      name: string;
      description?: string;
      income: boolean;
      expense: boolean;
    };
    CreateUserDto: {
      userName: string;
      admin: boolean;
      password: string;
    };
    UserDto: {
      userName: string;
      id?: number;
      version: number;
      admin: boolean;
    };
    SaveSharedWorkspaceRequestDto: {
      token: string;
    };
    TokenResponse: {
      token: string;
    };
    OAuth2AuthorizationCallbackRequest: {
      code?: string;
      error?: string;
      state: string;
    };
    LoginRequest: {
      userName: string;
      password: string;
      rememberMe: boolean;
    };
    ApiPageWorkspaceAccessTokenDto: {
      pageNumber: number;
      pageSize: number;
      totalElements: number;
      data: components["schemas"]["WorkspaceAccessTokenDto"][];
    };
    IncomeExpensesStatisticsItemDto: {
      categoryId?: number;
      totalAmount: number;
      finalizedCount: number;
      pendingCount: number;
      currencyExchangeDifference: number;
    };
    IncomesExpensesStatisticsDto: {
      items: components["schemas"]["IncomeExpensesStatisticsItemDto"][];
      totalAmount: number;
      finalizedCount: number;
      pendingCount: number;
      currencyExchangeDifference: number;
    };
    IncomeTaxPaymentsStatisticsDto: {
      totalTaxPayments: number;
    };
    FinalizedTaxSummaryItemDto: {
      tax: number;
      taxAmount: number;
      includedItemsNumber: number;
      includedItemsAmount: number;
    };
    GeneralTaxReportDto: {
      finalizedCollectedTaxes: components["schemas"]["FinalizedTaxSummaryItemDto"][];
      finalizedPaidTaxes: components["schemas"]["FinalizedTaxSummaryItemDto"][];
      pendingCollectedTaxes: components["schemas"]["PendingTaxSummaryItemDto"][];
      pendingPaidTaxes: components["schemas"]["PendingTaxSummaryItemDto"][];
    };
    PendingTaxSummaryItemDto: {
      tax: number;
      includedItemsNumber: number;
    };
    ApiPageInvoiceDto: {
      pageNumber: number;
      pageSize: number;
      totalElements: number;
      data: components["schemas"]["InvoiceDto"][];
    };
    ApiPageIncomeDto: {
      pageNumber: number;
      pageSize: number;
      totalElements: number;
      data: components["schemas"]["IncomeDto"][];
    };
    ApiPageIncomeTaxPaymentDto: {
      pageNumber: number;
      pageSize: number;
      totalElements: number;
      data: components["schemas"]["IncomeTaxPaymentDto"][];
    };
    ApiPageGeneralTaxDto: {
      pageNumber: number;
      pageSize: number;
      totalElements: number;
      data: components["schemas"]["GeneralTaxDto"][];
    };
    ApiPageExpenseDto: {
      pageNumber: number;
      pageSize: number;
      totalElements: number;
      data: components["schemas"]["ExpenseDto"][];
    };
    ApiPageDocumentDto: {
      pageNumber: number;
      pageSize: number;
      totalElements: number;
      data: components["schemas"]["DocumentDto"][];
    };
    GetDownloadTokenResponse: {
      token: string;
    };
    FluxDataBuffer: {
      prefetch?: number;
    };
    ApiPageCustomerDto: {
      pageNumber: number;
      pageSize: number;
      totalElements: number;
      data: components["schemas"]["CustomerDto"][];
    };
    ApiPageCategoryDto: {
      pageNumber: number;
      pageSize: number;
      totalElements: number;
      data: components["schemas"]["CategoryDto"][];
    };
    ApiPageUserDto: {
      pageNumber: number;
      pageSize: number;
      totalElements: number;
      data: components["schemas"]["UserDto"][];
    };
    CurrentUserPushNotificationMessage: {
      eventName: string;
      data?: { [key: string]: any };
    };
    DocumentsStorageStatus: {
      active: boolean;
    };
    GoogleDriveStorageIntegrationStatus: {
      folderId?: string;
      folderName?: string;
      authorizationUrl?: string;
      authorizationRequired: boolean;
    };
  };
}

export interface operations {
  editWorkspace: {
    parameters: {
      path: {
        workspaceId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["WorkspaceDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EditWorkspaceDto"];
      };
    };
  };
  getInvoice: {
    parameters: {
      path: {
        workspaceId: number;
        invoiceId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["InvoiceDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateInvoice: {
    parameters: {
      path: {
        workspaceId: number;
        invoiceId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["InvoiceDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EditInvoiceDto"];
      };
    };
  };
  getIncome: {
    parameters: {
      path: {
        workspaceId: number;
        incomeId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["IncomeDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateIncome: {
    parameters: {
      path: {
        workspaceId: number;
        incomeId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["IncomeDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EditIncomeDto"];
      };
    };
  };
  getTaxPayment: {
    parameters: {
      path: {
        workspaceId: number;
        taxPaymentId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["IncomeTaxPaymentDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateTaxPayment: {
    parameters: {
      path: {
        workspaceId: number;
        taxPaymentId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["IncomeTaxPaymentDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EditIncomeTaxPaymentDto"];
      };
    };
  };
  getTax: {
    parameters: {
      path: {
        workspaceId: number;
        taxId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["GeneralTaxDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateTax: {
    parameters: {
      path: {
        workspaceId: number;
        taxId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["GeneralTaxDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EditGeneralTaxDto"];
      };
    };
  };
  getExpense: {
    parameters: {
      path: {
        workspaceId: number;
        expenseId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ExpenseDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateExpense: {
    parameters: {
      path: {
        workspaceId: number;
        expenseId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ExpenseDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EditExpenseDto"];
      };
    };
  };
  getCustomer: {
    parameters: {
      path: {
        workspaceId: number;
        customerId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["CustomerDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateCustomer: {
    parameters: {
      path: {
        workspaceId: number;
        customerId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["CustomerDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EditCustomerDto"];
      };
    };
  };
  getProfile: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ProfileDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateProfile: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ProfileDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProfileRequestDto"];
      };
    };
  };
  getWorkspaces: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["WorkspaceDto"][];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createWorkspace: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["WorkspaceDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateWorkspaceDto"];
      };
    };
  };
  getAccessTokens: {
    parameters: {
      path: {
        workspaceId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ApiPageWorkspaceAccessTokenDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createToken: {
    parameters: {
      path: {
        workspaceId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["WorkspaceAccessTokenDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateWorkspaceAccessTokenDto"];
      };
    };
  };
  getInvoices: {
    parameters: {
      path: {
        workspaceId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ApiPageInvoiceDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createInvoice: {
    parameters: {
      path: {
        workspaceId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["InvoiceDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EditInvoiceDto"];
      };
    };
  };
  cancelInvoice: {
    parameters: {
      path: {
        workspaceId: number;
        invoiceId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["InvoiceDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getIncomes: {
    parameters: {
      path: {
        workspaceId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ApiPageIncomeDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createIncome: {
    parameters: {
      path: {
        workspaceId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["IncomeDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EditIncomeDto"];
      };
    };
  };
  getTaxPayments: {
    parameters: {
      path: {
        workspaceId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ApiPageIncomeTaxPaymentDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createTaxPayment: {
    parameters: {
      path: {
        workspaceId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["IncomeTaxPaymentDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EditIncomeTaxPaymentDto"];
      };
    };
  };
  getTaxes: {
    parameters: {
      path: {
        workspaceId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ApiPageGeneralTaxDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createTax: {
    parameters: {
      path: {
        workspaceId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["GeneralTaxDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EditGeneralTaxDto"];
      };
    };
  };
  getExpenses: {
    parameters: {
      path: {
        workspaceId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ApiPageExpenseDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createExpense: {
    parameters: {
      path: {
        workspaceId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ExpenseDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EditExpenseDto"];
      };
    };
  };
  getDocuments: {
    parameters: {
      path: {
        workspaceId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ApiPageDocumentDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  uploadNewDocument: {
    parameters: {
      path: {
        workspaceId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["DocumentDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          file?: string;
        };
      };
    };
  };
  getCustomers: {
    parameters: {
      path: {
        workspaceId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ApiPageCustomerDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createCustomer: {
    parameters: {
      path: {
        workspaceId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["CustomerDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EditCustomerDto"];
      };
    };
  };
  getCategories: {
    parameters: {
      path: {
        workspaceId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ApiPageCategoryDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createCategory: {
    parameters: {
      path: {
        workspaceId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["CategoryDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCategoryDto"];
      };
    };
  };
  getUsers: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ApiPageUserDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createUser: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["UserDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserDto"];
      };
    };
  };
  getSharedWorkspaces: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["WorkspaceDto"][];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  saveSharedWorkspace: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["WorkspaceDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SaveSharedWorkspaceRequestDto"];
      };
    };
  };
  refreshToken: {
    parameters: {
      cookie: {
        refreshToken?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TokenResponse"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  authCallback: {
    responses: {
      /** OK */
      200: unknown;
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OAuth2AuthorizationCallbackRequest"];
      };
    };
  };
  logout: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": string;
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  login_1: {
    parameters: {
      query: {
        sharedWorkspaceToken: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TokenResponse"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
  };
  getIncomesStatistics: {
    parameters: {
      path: {
        workspaceId: number;
      };
      query: {
        fromDate: string;
        toDate: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["IncomesExpensesStatisticsDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getTaxPaymentsStatistics: {
    parameters: {
      path: {
        workspaceId: number;
      };
      query: {
        fromDate: string;
        toDate: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["IncomeTaxPaymentsStatisticsDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getExpensesStatistics: {
    parameters: {
      path: {
        workspaceId: number;
      };
      query: {
        fromDate: string;
        toDate: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["IncomesExpensesStatisticsDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getCurrenciesShortlist: {
    parameters: {
      path: {
        workspaceId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": string[];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getGeneralTaxReport: {
    parameters: {
      path: {
        workspaceId: number;
      };
      query: {
        fromDate: string;
        toDate: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["GeneralTaxReportDto"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getDownloadToken: {
    parameters: {
      path: {
        workspaceId: number;
        documentId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["GetDownloadTokenResponse"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getDocumentContent: {
    parameters: {
      path: {
        workspaceId: number;
        documentId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["FluxDataBuffer"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getPushNotificationMessages: {
    responses: {
      /** OK */
      200: {
        content: {
          "text/event-stream": components["schemas"]["CurrentUserPushNotificationMessage"][];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getDocumentsStorageStatus: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["DocumentsStorageStatus"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getContent: {
    parameters: {
      query: {
        token: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["FluxDataBuffer"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getIntegrationStatus_1: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["GoogleDriveStorageIntegrationStatus"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getIntegrationStatus_6: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["GoogleDriveStorageIntegrationStatus"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getIntegrationStatus_3: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["GoogleDriveStorageIntegrationStatus"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getIntegrationStatus_5: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["GoogleDriveStorageIntegrationStatus"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getIntegrationStatus: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["GoogleDriveStorageIntegrationStatus"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getIntegrationStatus_2: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["GoogleDriveStorageIntegrationStatus"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getIntegrationStatus_4: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["GoogleDriveStorageIntegrationStatus"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
