spring:
  main:
    banner-mode: "off"
    web-application-type: servlet
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  graphql:
    http:
      path: "/api/graphql"
    websocket:
      path: "/api/graphql/subscriptions"

  datasource:
    url: jdbc:postgresql://${sa.database.host}:${sa.database.port}/${sa.database.name}
    username: "${sa.database.username}"
    password: "${sa.database.password}"

  security:
    oauth2:
      client:
        registration:
          google-drive:
            provider: "google"
            scope:
              - "https://www.googleapis.com/auth/drive.file"
            redirect-uri: "${sa.public-url}/oauth-callback"
            client-id: "${sa.documents.storage.google-drive.client-id}"
            client-secret: "${sa.documents.storage.google-drive.client-secret}"

  jpa:
    properties:
      hibernate.create_empty_composites.enabled: true
  web:
    resources:
      add-mappings: false
  flyway:
    locations: classpath:db/migration
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-null-for-primitives: true

server:
  port: 9393
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false

sa:
  public-url: "https://simple-accounting.orange-buffalo.io"
  database:
    username: "sa"
    password: ""
    host: "localhost"
    port: 5432
    name: "simple-accounting"
    legacy-h2-path: /data/db/simple-accounting
  documents:
    storage:
      local-fs:
        enabled: false
        base-directory: /data/documents-storage/local
      google-drive:
        base-api-url: "https://www.googleapis.com"
        client-id: "<replace>"
        client-secret: "<replace>"
---

spring:
  datasource:
    url: jdbc:postgresql://${sa.database.host}:${sa.database.port}/${sa.database.name}

  security:
    oauth2:
      client:
        registration:
          google-drive:
            redirect-uri: "http://localhost:9393/oauth-callback"
  config:
    activate:
      on-profile: development

sa:
  database:
    legacy-h2-path: ./local-dev/dev
    legacy-h2-username: bender
    legacy-h2-password: killallhumans
  documents:
    storage:
      local-fs:
        base-directory: ./local-dev/documents

---

spring:
  security:
    oauth2:
      client:
        registration:
          google-drive:
            client-id: "noop"
            client-secret: "noop"
            redirect-uri: "http://ci-tests/noop"
  config:
    activate:
      on-profile: ci-tests

---

spring:
  security:
    oauth2:
      client:
        registration:
          google-drive:
            client-id: "noop"
            client-secret: "noop"
            redirect-uri: "http://ci-tests/noop"
  config:
    activate:
      on-profile: load-tests
