spring:
  main:
    banner-mode: "off"
    web-application-type: reactive

  datasource:
    url: jdbc:h2:/data/db/simple-accounting

  security:
    oauth2:
      client:
        registration:
          google-drive:
            provider: "google"
            scope:
              - "https://www.googleapis.com/auth/drive.file"
            redirect-uri: "https://simple-accounting.orange-buffalo.io/oauth-callback"

  jpa:
    properties:
      hibernate.create_empty_composites.enabled: true
  web:
    resources:
      add-mappings: false
  flyway:
    baseline-on-migrate: true
    baseline-version: "0001"

server:
  port: 9393
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false

simpleaccounting:
  documents:
    storage:
      local-fs:
        base-directory: /data/documents-storage/local
      google-drive:
        base-api-url: "https://www.googleapis.com"

---

spring:
  datasource:
    url: jdbc:h2:./local-dev/dev
    password: killallhumans
    username: bender

  security:
    oauth2:
      client:
        registration:
          google-drive:
            redirect-uri: "http://localhost:9393/oauth-callback"
  config:
    activate:
      on-profile: development

simpleaccounting:
  documents:
    storage:
      local-fs:
        base-directory: ./local-dev/documents

---

spring:
  datasource:
    url: jdbc:h2:mem:ci-tests

  security:
    oauth2:
      client:
        registration:
          google-drive:
            client-id: "noop"
            client-secret: "noop"
            redirect-uri: "http://ci-tests/noop"
  config:
    activate:
      on-profile: ci-tests

---

spring:
  datasource:
    url: jdbc:h2:/tmp/sa-load-tests

  security:
    oauth2:
      client:
        registration:
          google-drive:
            client-id: "noop"
            client-secret: "noop"
            redirect-uri: "http://ci-tests/noop"
  config:
    activate:
      on-profile: load-tests
