/* [jooq ignore start] */

alter table income
alter column id bigint generated by default as identity not null;

alter table invoice
alter column id bigint generated by default as identity not null;

alter table expense
alter column id bigint generated by default as identity not null;

/* [jooq ignore stop] */
