name: 'Setup Project Environment'
description: 'Sets up the development environment for Simple Accounting project'
inputs:
  setup-playwright:
    description: 'Whether to install Playwright dependencies'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: "Set up JDK"
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: "Setup Bun"
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: "Cache Bun dependencies"
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-${{ hashFiles('frontend/bun.lock', 'frontend/package.json') }}
        path: ~/.bun/install/cache

    - name: "Setup Gradle"
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: wrapper
        # disable reading from cache on re-runs to fix possible caching issues
        cache-write-only: ${{ fromJSON(github.run_attempt) != 1 }}

    - name: "Setup Playwright"
      if: inputs.setup-playwright == 'true'
      shell: bash
      run: ./gradlew installPlaywrightDependencies --console=plain --build-cache