object Versions {
    const val springBoot = "2.4.5"
    const val springDependencyManagement = "1.0.11.RELEASE"
    const val kotlin = "1.5.0"
    const val kotlinCoroutines = "1.4.3"
    const val kotlinLogging = "1.12.5"
    const val arrow = "0.13.2"
    const val jjwt = "0.11.2"
    const val javaxEl = "3.0.1-b12"
    const val guava = "30.1.1-jre"
    const val jooq = "3.14.9"

    const val assertk = "0.24"
    const val mockito = "3.10.0"
    const val mockitoKotlin = "2.2.0"
    const val jsonUnit = "2.25.0"
    const val wireMock = "2.28.0"
    const val awaitility = "4.1.0"
    const val selenide = "5.20.4"
    const val testContainers = "1.15.3"
    const val zjsonpatch = "0.4.11"
    const val springdocOpenapi = "1.5.8"

    const val dockerPlugin = "7.0.0"
    const val semverGitPlugin = "1.2.1"
    const val versionsPlugin = "0.38.0"
}
