object Versions {
    const val springBoot = "3.0.4"
    const val springDependencyManagement = "1.0.11.RELEASE"
    const val kotlin = "1.8.10"
    const val kotlinCoroutines = "1.6.4"
    const val kotlinLogging = "3.0.5"
    const val arrow = "1.1.4"
    const val jjwt = "0.11.5"
    const val javaxEl = "3.0.1-b12"
    const val guava = "31.1-jre"
    const val jooq = "3.16.16"

    const val assertk = "0.25"
    const val mockito = "5.2.0"
    const val mockitoKotlin = "2.2.0"
    const val jsonUnit = "2.36.1"
    const val wireMock = "2.35.0"
    const val awaitility = "4.2.0"
    const val selenide = "6.5.1"
    const val selenium = "4.2.0"
    const val testContainers = "1.17.6"
    const val zjsonpatch = "0.4.14"
    const val springdocOpenapi = "2.0.4"

    const val semverGitPlugin = "1.2.1"
    const val versionsPlugin = "0.46.0"
}
