package io.orangebuffalo.accounting.simpleaccounting.services.persistence.repos

import io.orangebuffalo.accounting.simpleaccounting.services.persistence.entities.SavedWorkspaceAccessToken

interface SavedWorkspaceAccessTokenRepository : AbstractEntityRepository<SavedWorkspaceAccessToken>