spring:
  main:
    banner-mode: "off"

  datasource:
    url: jdbc:h2:/data/db/simple-accounting

server:
  port: 9393

simpleaccounting:
  documents:
    storage:
      local-fs:
        base-directory: /data/documents-storage/local
      google-drive:
        credentials-file: file:/data/documents-storage/google-drive/client-secret.json
        data-store-directory: /data/documents-storage/google-drive/data-storage

---

spring:
  profiles: development

  datasource:
    url: jdbc:h2:./local-dev/dev
    password: killallhumans
    username: bender

simpleaccounting:
  documents:
    storage:
      local-fs:
        base-directory: ./local-dev/documents
      google-drive:
        credentials-file: file:./local-dev/gdrive/client_secret.json
        data-store-directory: ./local-dev/gdrive/data-store
        redirect-url-base: http://localdev.orange-buffalo.io:9393