spring:
  main:
    banner-mode: "off"

  datasource:
    url: jdbc:h2:/data/db/simple-accounting

  security:
    oauth2:
      client:
        registration:
          google-drive:
            provider: "google"
            scope:
              - "https://www.googleapis.com/auth/drive.file"
            redirect-uri: "https://simple-accounting.orange-buffalo.io/api/v1/auth/oauth2/callback"

server:
  port: 9393

simpleaccounting:
  documents:
    storage:
      local-fs:
        base-directory: /data/documents-storage/local

---

spring:
  profiles: development

  datasource:
    url: jdbc:h2:./local-dev/dev
    password: killallhumans
    username: bender

  security:
    oauth2:
      client:
        registration:
          google-drive:
            redirect-uri: "http://localdev.orange-buffalo.io:9393/api/v1/auth/oauth2/callback"

simpleaccounting:
  documents:
    storage:
      local-fs:
        base-directory: ./local-dev/documents
      google-drive:
        credentials-file: file:./local-dev/gdrive/client_secret.json
        data-store-directory: ./local-dev/gdrive/data-store
        redirect-url-base: http://localdev.orange-buffalo.io:9393