spring:
  main:
    banner-mode: "off"
    web-application-type: reactive

  datasource:
    url: jdbc:h2:/data/db/simple-accounting

  security:
    oauth2:
      client:
        registration:
          google-drive:
            provider: "google"
            scope:
              - "https://www.googleapis.com/auth/drive.file"
            redirect-uri: "https://simple-accounting.orange-buffalo.io/api/auth/oauth2/callback"

  resources:
    add-mappings: false

  jpa:
    properties:
      hibernate.create_empty_composites.enabled: true

server:
  port: 9393
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false

simpleaccounting:
  documents:
    storage:
      local-fs:
        base-directory: /data/documents-storage/local
      google-drive:
        base-api-url: "https://www.googleapis.com"

---

spring:
  profiles: development

  datasource:
    url: jdbc:h2:./local-dev/dev
    password: killallhumans
    username: bender

  security:
    oauth2:
      client:
        registration:
          google-drive:
            redirect-uri: "http://localdev.orange-buffalo.io:9393/api/auth/oauth2/callback"

simpleaccounting:
  documents:
    storage:
      local-fs:
        base-directory: ./local-dev/documents

---

spring:
  profiles: ci-tests

  datasource:
    url: jdbc:h2:mem:ci-tests

  security:
    oauth2:
      client:
        registration:
          google-drive:
            client-id: "noop"
            client-secret: "noop"
            redirect-uri: "http://ci-tests/noop"

---

spring:
  profiles: load-tests

  datasource:
    url: jdbc:h2:/tmp/sa-load-tests

  security:
    oauth2:
      client:
        registration:
          google-drive:
            client-id: "noop"
            client-secret: "noop"
            redirect-uri: "http://ci-tests/noop"
