spring:
  main:
    banner-mode: "off"

---

spring:
  profiles: development

  datasource:
    url: jdbc:h2:./local-dev/dev
    password: killallhumans
    username: bender

server:
  port: 9393

simpleaccounting:
  documents:
    storage:
      local-fs:
        base-directory: ./local-dev/documents
      google-drive:
        credentials-file: file:./local-dev/gdrive/client_secret.json
        data-store-directory: ./local-dev/gdrive/data-store
        redirect-url-base: http://localdev.orange-buffalo.io:9393