package io.orangebuffalo.simpleaccounting.infra.ui

import com.fasterxml.jackson.databind.DeserializationFeature
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import com.fasterxml.jackson.module.kotlin.readValue
import com.microsoft.playwright.Browser
import com.microsoft.playwright.Page
import io.orangebuffalo.simpleaccounting.infra.utils.KNginxContainer
import io.orangebuffalo.simpleaccounting.infra.utils.logger
import io.orangebuffalo.simpleaccounting.infra.utils.yamlObjectMapper
import io.orangebuffalo.testcontainers.playwright.PlaywrightContainer
import mu.KotlinLogging
import org.junit.jupiter.api.extension.*
import org.testcontainers.containers.BindMode
import org.testcontainers.containers.Network
import org.testcontainers.containers.wait.strategy.HttpWaitStrategy
import java.io.File
import java.net.URI

private val testConfig = loadTestConfig()

private val chromeLogger = KotlinLogging.logger("chrome")

private val network: Network = Network.newNetwork()

private val storybookEnvironment = StorybookEnvironment()

private const val storybookDirectory = "../frontend/build/storybook"

private val nginx = KNginxContainer("nginx:1.22")
    .withCustomContent(storybookDirectory)
    .waitingFor(HttpWaitStrategy())
    .withNetwork(network)
    .withNetworkAliases("storybook")
    // nginx does not support mjs generated by storybook, overriding config to enable it
    .withClasspathResourceMapping("/nginx.conf", "/etc/nginx/nginx.conf", BindMode.READ_ONLY)

private val chrome: PlaywrightContainer = PlaywrightContainer()
    .withNetwork(network)
    .withLogConsumer { frame -> chromeLogger.info(frame.utf8String) }
    .withNetwork(network)
    .withExtraHost("host.docker.internal", "host-gateway")

class StorybookExtension : BeforeEachCallback, Extension, ParameterResolver {
    override fun beforeEach(context: ExtensionContext) {
        // lazy start the container for easier debugging in IDE
        // but keep singleton containers as they start slowly
        if (!chrome.isRunning) {
            chrome.start()
            if (testConfig.useCompliedStorybook) {
                nginx.start()
            }
        }
    }

    override fun supportsParameter(parameterContext: ParameterContext, extensionContext: ExtensionContext): Boolean {
        return parameterContext.parameter.type == StorybookEnvironment::class.java
    }

    override fun resolveParameter(parameterContext: ParameterContext, extensionContext: ExtensionContext): Any {
        return storybookEnvironment
    }
}

class StorybookEnvironment {

    val stories: Collection<StorybookStory>
    val shouldUpdateCommittedScreenshots: Boolean
        get() = testConfig.replaceCommittedFiles

    private val pages = ThreadLocal.withInitial {
            val browser = chrome.getPlaywrightApi().chromium()
            val context = browser.newContext(
                Browser.NewContextOptions()
                    .setBaseURL(
                        if (testConfig.useCompliedStorybook)
                            "http://storybook/"
                        else "http://host.docker.internal:6006/"
                    )
                    .setViewportSize(1358, 687)
            )
            context.setDefaultTimeout(10_000.0)

            Runtime.getRuntime().addShutdownHook(Thread {
                browser.close()
            })

            context.newPage()
        }

    init {
        val storiesJsonUri = if (testConfig.useCompliedStorybook)
            File(storybookDirectory, "stories.json").toURI()
        else URI("http://localhost:6006/stories.json")

        val data: StorybookStoriesFileData = jacksonObjectMapper()
            .disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES).readValue(storiesJsonUri.toURL())

        val excludedStories = setOf(
            "components-basic-documents-sadocumentslist--with-deferred-documents",
            "components-basic-documents-sadocumentsupload--with-deferred-documents",
            "components-basic-documents-sadocumentsupload--initial-loading-with-no-documents",
            "components-basic-documents-sadocumentsupload--all-uploads-failing",
            "components-other-notifications--error",
        )
        excludedStories.forEach { skippedStoryId ->
            if (data.stories.values.firstOrNull { story -> story.id == skippedStoryId } == null) {
                throw IllegalStateException("Skipped story $skippedStoryId does not exist")
            }
        }
        stories = data.stories.values.filter { story -> !excludedStories.contains(story.id) }
    }

    fun page(): Page = pages.get()
}

data class StorybookStory(
    val title: String,
    val name: String,
    val id: String,
)

private data class StorybookStoriesFileData(
    val stories: Map<String, StorybookStory>
)

private data class TestConfig(
    val replaceCommittedFiles: Boolean = false,
    val useCompliedStorybook: Boolean = true,
)

private fun loadTestConfig(): TestConfig {
    val testConfigFile = File("src/test/.test-config.yaml")
    val config: TestConfig = if (testConfigFile.exists())
        yamlObjectMapper().readValue(testConfigFile)
    else TestConfig()
    logger.info { "Loaded test config: $config" }
    return config
}
