package io.orangebuffalo.simpleaccounting.domain.users

import io.orangebuffalo.simpleaccounting.services.persistence.repos.AbstractEntityRepository

interface UserActivationTokenRepository : AbstractEntityRepository<UserActivationToken>
