name: Dependencies upgrade auto-merge
on: pull_request

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: export GH_TOKEN=${{ secrets.DEPENDABOT_AUTO_REBASE_TOKEN }} && gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.DEPENDABOT_AUTO_REBASE_TOKEN }}
