name: Rebase Dependabot stale PRs

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  rebase-dependabot:
    runs-on: ubuntu-latest
    steps:
    - name: rebase
      uses: orange-buffalo/dependabot-auto-rebase@v1
      with:
        api-token: ${{ secrets.DEPENDABOT_AUTO_REBASE_TOKEN }}
        repository: ${{ github.repository }}
